language: node_js

env:
  - DATABASE_URL = 'postgresql://postgres@localhost:5432/greetings_tests';

node_js:  
  - "8.11.3"

before_script:
  - psql -c 'create database  greetings_tests;' -U postgres
  - psql -U postgres -d greetings_tests -a -f table.sql

  
addons:
    apt:
    packages:
    - postgresql-server-dev-9.2